# Sofle RGB MX v1 on nice!nano v2

# Rotary encoders on both halves.
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 36 WS2812 LEDs per half (72 LEDs total).
CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment if SSD1306 OLED displays are installed.
# CONFIG_ZMK_DISPLAY=y
